apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 2
  source:
    helm:
      valueFiles:
        - values.yaml
        - config/common/aws-values.yaml
        - config/demo/values.yaml
      parameters:
        - name: thanosServer
          value: https://thanos-gateway.multicloud-ibm.com/demo0
    path: observability
    repoURL: 'git@github.com:code-noggin/argotest.git'
    targetRevision: HEAD
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
