apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 2
  source:
    helm:
      valueFiles:
        - config/common/aws-values.yaml
        - config/demo/values.yaml
      parameters: []
    path: continuous-delivery-usecase/argocd-pipeline/applications/demo-environment
    directory: git@github.kyndryl.net:pstatham/sandbox.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
